<a href="https://colab.research.google.com/github/sibasishsahu68/DMPM-Lab/blob/main/Experiment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Z - Score Normalization
x = ([10,20,30,40,50])
mean = sum(x)/len(x)
variance = sum((xi - mean)**2 for xi in x)/len(x)
std_dev = variance**0.5
z = [(xi - mean)/std_dev for xi in x]
print("\nZ-Sdcore Normalization values are :",z)

#min-max normalization
x = ([10,20,30,40,50])
min_val = min(x)
max_val = max(x)
normalized = [(xi - min_val)/(max_val - min_val) for xi in x]
print("\nMin-Max Normalization values are:",normalized)

#decimal scaling
import math
x = ([10,20,30,40,50])
i = math.floor(math.log10(max(x)))
normalized = [xi/(10**i) for xi in x]
print("\nDecimal Scaling values are:",normalized)

Z-Sdcore Normalization values are : [-1.414213562373095, -0.7071067811865475, 0.0, 0.7071067811865475, 1.414213562373095]

Min-Max Normalization values are: [0.0, 0.25, 0.5, 0.75, 1.0]

Decimal Scaling values are: [1.0, 2.0, 3.0, 4.0, 5.0]

In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('/content/Titanic-Dataset.csv')

df = df.drop('Name', axis=1)
display(df.head())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
import math
max_fare_abs = df['Fare'].abs().max()

if max_fare_abs > 0:
    j = math.floor(math.log10(max_fare_abs))
else:
    j = 0
df['Fare_Decimal_Scaled'] = df['Fare'] / (10**j)

display(df[['Fare', 'Fare_Decimal_Scaled']].head(10))

      Fare  Fare_Decimal_Scaled
0   7.2500             0.072500
1  71.2833             0.712833
2   7.9250             0.079250
3  53.1000             0.531000
4   8.0500             0.080500
5   8.4583             0.084583
6  51.8625             0.518625
7  21.0750             0.210750
8  11.1333             0.111333
9  30.0708             0.300708

In [25]:
min_age = df['Age'].min()
max_age = df['Age'].max()
df['Age_MinMax_Scaled'] = (df['Age'] - min_age) / (max_age - min_age)

min_fare = df['Fare'].min()
max_fare = df['Fare'].max()
df['Fare_MinMax_Scaled'] = (df['Fare'] - min_fare) / (max_fare - min_fare)

display(df[['Age', 'Age_MinMax_Scaled', 'Fare', 'Fare_MinMax_Scaled']].head(10))

    Age  Age_MinMax_Scaled     Fare  Fare_MinMax_Scaled
0  22.0           0.271174   7.2500            0.014151
1  38.0           0.472229  71.2833            0.139136
2  26.0           0.321438   7.9250            0.015469
3  35.0           0.434531  53.1000            0.103644
4  35.0           0.434531   8.0500            0.015713
5   NaN                NaN   8.4583            0.016510
6  54.0           0.673285  51.8625            0.101229
7   2.0           0.019854  21.0750            0.041136
8  27.0           0.334004  11.1333            0.021731
9  14.0           0.170646  30.0708            0.058694

In [26]:
mean_age = df['Age'].mean()
std_age = df['Age'].std()
df['Age_ZScore_Scaled'] = (df['Age'] - mean_age) / std_age

mean_fare = df['Fare'].mean()
std_fare = df['Fare'].std()
df['Fare_ZScore_Scaled'] = (df['Fare'] - mean_fare) / std_fare

display(df[['Age', 'Age_ZScore_Scaled', 'Fare', 'Fare_ZScore_Scaled']].head(10))

    Age  Age_ZScore_Scaled     Fare  Fare_ZScore_Scaled
0  22.0          -0.530005   7.2500           -0.502163
1  38.0           0.571430  71.2833            0.786404
2  26.0          -0.254646   7.9250           -0.488580
3  35.0           0.364911  53.1000            0.420494
4  35.0           0.364911   8.0500           -0.486064
5   NaN                NaN   8.4583           -0.477848
6  54.0           1.672866  51.8625            0.395591
7   2.0          -1.906799  21.0750           -0.223957
8  27.0          -0.185807  11.1333           -0.424018
9  14.0          -1.080723  30.0708           -0.042931